"""Postgers

Revision ID: f6d6e10bccde
Revises: e611b00ef4da
Create Date: 2024-12-01 20:49:42.363597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d6e10bccde'
down_revision: Union[str, None] = 'e611b00ef4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
